ID="kablonet"
NAME="KABLONET (TÜRKSAT)"
SOURCE="KZSC native preset: Kablonet"
HTTP_OPT="--filter-tcp=80 --filter-l7=http --payload=http_req --lua-desync=multisplit:ip_ttl=2 --new"
TLS_OPT="--filter-tcp=443 --filter-l7=tls --payload=tls_client_hello --lua-desync=multidisorder:pos=2:seqovl=1"
UDP_OPT=""
NO_UDP="1"
MATCH="KABLONET|TURKSAT|KABLO"
