# SPDX-License-Identifier: MIT
# Original KZSC baseline; legacy ID retained only for saved selections.
# Same unvalidated TCP baseline for every ISP. Run Blockcheck on this WAN.
ID="kablonet"
NAME="Kablonet"
SOURCE="Original KZSC baseline; ISP validation required / ISS üzerinde Blockcheck gerekli"
HTTP_OPT="--filter-tcp=80 --filter-l7=http --payload=http_req --lua-desync=multisplit:pos=host+1 --new"
TLS_OPT="--filter-tcp=443 --filter-l7=tls --payload=tls_client_hello --lua-desync=multisplit:pos=1,sniext+2"
UDP_OPT=""
NO_UDP="1"
MATCH=""
