ID="sol"
NAME="SUPERONLINE (SOL)"
SOURCE="KZSC native preset: Superonline"
HTTP_OPT="--filter-tcp=80 --filter-l7=http --payload=http_req --lua-desync=http_hostcase:spell=hoSt --new"
TLS_OPT="--filter-tcp=443 --filter-l7=tls --payload=tls_client_hello --lua-desync=fake:blob=fake_default_tls:ip_ttl=6:repeats=1"
UDP_OPT=""
NO_UDP="1"
MATCH="SUPERONLINE"
