ID="tt"
NAME="TURK TELEKOM (TT)"
SOURCE="KZSC native preset: Turk Telekom"
HTTP_OPT="--filter-tcp=80 --filter-l7=http --payload=http_req --lua-desync=fake:blob=fake_default_http:ip_ttl=2:repeats=1 --new"
TLS_OPT="--filter-tcp=443 --filter-l7=tls --payload=tls_client_hello --lua-desync=fake:blob=fake_default_tls:ip_ttl=2:repeats=1 --new"
UDP_OPT="--filter-udp=443 --filter-l7=quic --payload=quic_initial --lua-desync=fake:blob=fake_default_quic:ip_ttl=2:repeats=6"
NO_UDP="0"
MATCH="TURK TELEKOM|TTNET"
